### ISSUE TITLE
cannot import name '_BaseUrl' from 'pydantic.networks'

### ISSUE THREAD

**Issue by ohdearquant** [jlowin/fastmcp#39]
## fastmcp version

```
fastmcp = "0.3.3"
```

## dependency management
- poetry

## Error

```
(.venv) (base) lion@Mac dev_mcp % fastmcp install fast_.py
Traceback (most recent call last):
  File "/Users/lion/playground/.venv/bin/fastmcp", line 5, in <module>
    from fastmcp.cli import app
  File "/Users/lion/playground/.venv/lib/python3.12/site-packages/fastmcp/__init__.py", line 4, in <module>
    from .server import FastMCP, Context
  File "/Users/lion/playground/.venv/lib/python3.12/site-packages/fastmcp/server.py", line 42, in <module>
    from fastmcp.resources import FunctionResource, Resource, ResourceManager
  File "/Users/lion/playground/.venv/lib/python3.12/site-packages/fastmcp/resources/__init__.py", line 1, in <module>
    from .base import Resource
  File "/Users/lion/playground/.venv/lib/python3.12/site-packages/fastmcp/resources/base.py", line 16, in <module>
    from pydantic.networks import _BaseUrl  # TODO: remove this once pydantic is updated
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name '_BaseUrl' from 'pydantic.networks' (/Users/lion/playground/.venv/lib/python3.12/site-packages/pydantic/networks.py)
```

## To re-produce

```python
# fast_.py

from fastmcp import FastMCP


# Create an MCP server
mcp = FastMCP("Demo")


# Add an addition tool
@mcp.tool()
def add(a: int, b: int) -> int:
    """Add two numbers"""
    return a + b


# Add a dynamic greeting resource
@mcp.resource("greeting://{name}")
def get_greeting(name: str) -> str:
    """Get a personalized greeting"""
    return f"Hello, {name}!"
```

```
cd dev_mcp
fastmcp install fast_.py
```

**Comment by jlowin** [comment]
Super weird, I'm able to replicate manually but not by running the `install` command the way you hit it -- will get a fix out ASAP.

**Comment by jlowin** [comment]
Fix should go out in https://github.com/jlowin/fastmcp/releases/tag/v0.3.4

**Comment by ohdearquant** [comment]
that's super quick, will try, thanks
